import turtle

def graphical_Fri53(overweight: list, oversold: list, layover: list) -> None:
    """ This takes in overweight, oversold, and layover data and presents it aesthetically using turtle
        Our group only had 4 people so time_delay was not implemented
    """
    # Constants 
    SCREEN_WIDTH = 900
    SCREEN_HEIGHT = 600
    WINDOW_TITLE = "Graphical_Fri53()"
    
    # Set up the screen object
    turtle.setup(SCREEN_WIDTH, SCREEN_HEIGHT)
    screen = turtle.Screen()
    screen.title(WINDOW_TITLE)
    screen.bgcolor("thistle")
    
    # Create the turtle object
    t = turtle.Turtle()

    # creating basic layout    
    t.penup()
    t.begin_fill()
    t.fillcolor("darkorchid")
    t.goto(-400, 200)
    t.pendown() 
    t.goto(-237.5, 200)
    t.goto(-237.5, 250)
    t.goto(-400, 250)
    t.goto(-400, 200)
    t.end_fill()
    t.hideturtle()
    
    # Boeing 777-300ER col
    t.penup()
    t.goto(-325, 212.5) 
    t.pendown() 
    t.pencolor("white") 
    t.write(f"Boeing 777-300ER", align="center", font=("Arial", 13, "normal", "bold"))
    t.penup()
    t.goto(-400, 170) 
    t.pendown()
    t.pencolor("black")
    t.write("Oversold Business Seats: {}".format(oversold[0][-1][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-400, 140) 
    t.pendown()
    t.write("Oversold Economy Seats: {}".format(oversold[1][-1][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-400, 110)
    t.pendown() 
    t.write("Overweight Bags: {}".format(overweight[0][-1][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-400, 80) 
    t.pendown()
    t.write("Layover Passengers: {}".format(layover[0][-1][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-400, 50) 
    t.pendown()
    t.write("Late Layover Passengers: ", align="left", font=("Arial", 8, "normal"))
    t.hideturtle()
    
    # Boeing 777-200LR col
    t.penup()
    t.begin_fill()
    t.fillcolor("darkorchid")
    t.goto(-187.5, 200)
    t.pendown() 
    t.goto(-25, 200)
    t.goto(-25, 250)
    t.goto(-187.5, 250)
    t.goto(-187.5, 200)
    t.end_fill()
    t.hideturtle()
    
    t.penup()
    t.goto(-112.5, 212.5) 
    t.pendown() 
    t.pencolor("white") 
    t.write("Boeing 777-200LR", align="center", font=("Arial", 13, "normal", "bold"))
    t.penup()
    t.goto(-187.5, 170) 
    t.pendown()
    t.pencolor("black")
    t.write("Oversold Business Seats: {}".format(oversold[0][-2][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-187.5, 140) 
    t.pendown()
    t.write("Oversold Economy Seats: {}".format(oversold[1][-2][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-187.5, 110)
    t.pendown() 
    t.write("Overweight Bags: {}".format(overweight[0][-2][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-187.5, 80) 
    t.pendown()
    t.write("Layover Passengers: {}".format(layover[0][-2][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-187.5, 50) 
    t.pendown()
    t.write(f"Late Layover Passengers: ", align="left", font=("Arial", 8, "normal"))
    
    # Airbus A330-300 col
    t.penup()
    t.begin_fill()
    t.fillcolor("darkorchid")
    t.goto(25, 200)
    t.pendown() 
    t.goto(187.5, 200)
    t.goto(187.5, 250)
    t.goto(25, 250)
    t.goto(25, 200)
    t.end_fill()
    t.hideturtle()
    
    t.penup()
    t.goto(100, 212.5) 
    t.pendown() 
    t.pencolor("white") 
    t.write(f"Airbus A330-300", align="center", font=("Arial", 13, "normal", "bold"))
    t.penup()
    t.goto(25, 170) 
    t.pendown()
    t.pencolor("black")
    t.write("Oversold Business Seats: {}".format(oversold[0][1][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(25, 140) 
    t.pendown()
    t.write("Oversold Economy Seats: {}".format(oversold[1][1][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(25, 110)
    t.pendown() 
    t.write("Overweight Bags: {}".format(overweight[0][1][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(25, 80) 
    t.pendown()
    t.write("Layover Passengers: {}".format(layover[0][1][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(25, 50) 
    t.pendown()
    t.write(f"Late Layover Passengers: ", align="left", font=("Arial", 8, "normal"))
    
    # Embraer A330-300 col
    t.penup()
    t.begin_fill()
    t.fillcolor("darkorchid")
    t.goto(237.5, 200)
    t.pendown() 
    t.goto(400, 200)
    t.goto(400, 250)
    t.goto(237.5, 250)
    t.goto(237.5, 200)
    t.end_fill()
    t.hideturtle()
    
    t.penup()
    t.goto(312.5, 212.5) 
    t.pendown() 
    t.pencolor("white") 
    t.write("Embraer A330-300", align="center", font=("Arial", 13, "normal", "bold"))
    t.penup()
    t.goto(237.5, 170) 
    t.pendown()
    t.pencolor("black")
    t.write("Oversold Business Seats: {}".format(oversold[0][0][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(237.5, 140) 
    t.pendown()
    t.write("Oversold Economy Seats: {}".format(oversold[1][0][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(237.5, 110)
    t.pendown() 
    t.write("Overweight Bags: {}".format(overweight[0][0][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(237.5, 80) 
    t.pendown()
    t.write("Layover Passengers: {}".format(layover[0][0][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(237.5, 50) 
    t.pendown()
    t.write(f"Late Layover Passengers: ", align="left", font=("Arial", 8, "normal"))
    
    # Airbus A319-100 col
    t.penup()
    t.begin_fill()
    t.fillcolor("darkorchid")
    t.goto(-368.75, 0)
    t.pendown() 
    t.goto(-206.25, 0)
    t.goto(-206.25, -50)
    t.goto(-368.75, -50)
    t.goto(-368.75, 0)
    t.end_fill()
    t.hideturtle()
    
    t.penup()
    t.goto(-293.75, -35) 
    t.pendown() 
    t.pencolor("white") 
    t.write(f"Airbus A319-100", align="center", font=("Arial", 13, "normal", "bold"))
    t.penup()
    t.goto(-368.75, -80) 
    t.pendown()
    t.pencolor("black")
    t.write("Oversold Business Seats: {}".format(oversold[0][2][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-368.75, -110) 
    t.pendown()
    t.write("Oversold Economy Seats: {}".format(oversold[1][2][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-368.75, -140)
    t.pendown() 
    t.write("Overweight Bags: {}".format(overweight[0][2][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-368.75, -170) 
    t.pendown()
    t.write("Layover Passengers: {}".format(layover[0][2][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-368.75, -200) 
    t.pendown()
    t.write(f"Late Layover Passengers: ", align="left", font=("Arial", 8, "normal"))
    
    # Boeing 737 MAX 8 col
    t.penup()
    t.begin_fill()
    t.fillcolor("darkorchid")
    t.goto(-81.25, 0)
    t.pendown() 
    t.goto(81.25, 0)
    t.goto(81.25, -50)
    t.goto(-81.25, -50)
    t.goto(-81.25, 0)
    t.end_fill()
    t.hideturtle()
    
    t.penup()
    t.goto(-6.25, -35) 
    t.pendown() 
    t.pencolor("white") 
    t.write("Boeing 737 MAX 8", align="center", font=("Arial", 13, "normal", "bold"))
    t.penup()
    t.goto(-81.25, -80) 
    t.pendown()
    t.pencolor("black")
    t.write("Oversold Business Seats: {}".format(oversold[0][3][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-81.25, -110) 
    t.pendown()
    t.write("Oversold Economy Seats: {}".format(oversold[1][3][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-81.25, -140)
    t.pendown() 
    t.write("Overweight Bags: {}".format(overweight[0][3][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-81.25, -170) 
    t.pendown()
    t.write("Layover Passengers: {}".format(layover[0][3][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(-81.25, -200) 
    t.pendown()
    t.write(f"Late Layover Passengers: ", align="left", font=("Arial", 8, "normal"))
    
    # Airbus A321-200 col
    t.penup()
    t.begin_fill()
    t.fillcolor("darkorchid")
    t.goto(206.25, 0)
    t.pendown() 
    t.goto(368.75, 0)
    t.goto(368.75, -50)
    t.goto(206.25, -50)
    t.goto(206.25, 0)
    t.end_fill()
    t.hideturtle()
    
    t.penup()
    t.goto(281.25, -35) 
    t.pendown() 
    t.pencolor("white") 
    t.write("Airbus A321-200", align="center", font=("Arial", 13, "normal", "bold"))
    t.penup()
    t.goto(206.25, -80) 
    t.pendown()
    t.pencolor("black")
    t.write("Oversold Business Seats: {}".format(oversold[0][4][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(206.25, -110) 
    t.pendown()
    t.write("Oversold Economy Seats: {}".format(oversold[1][4][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(206.25, -140)
    t.pendown() 
    t.write("Overweight Bags: {}".format(overweight[0][4][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(206.25, -170) 
    t.pendown()
    t.write("Layover Passengers: {}".format(layover[0][4][1]), align="left", font=("Arial", 8, "normal"))
    t.penup()
    t.goto(206.25, -200) 
    t.pendown()
    t.write("Late Layover Passengers: ", align="left", font=("Arial", 8, "normal"))
    
    # Make a clean exit
    screen.exitonclick() 
    t.done()